apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gonexus0206a 
  janus-idp.io/tekton: gonexus0206a
  backstage.io/kubernetes-id: gonexus0206a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gonexus0206a
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  