apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gonexus0206a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gonexus0206a 
  name: gonexus0206a
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gonexus0206a 
